/******************************************************************************
 *
 * Module: HC-SR04
 *
 * File Name:  HC-SR04.h
 *
 * Description: Header file for the AVR HC-SR04 Ultrasonic driver
 *
 * Author: Hisham Elsayed
 *
 *******************************************************************************/

#ifndef HC_SR04_H_
#define HC_SR04_H_

#include "std_types.h"

/*******************************************************************************
 *                                Definitions                                  *
 *******************************************************************************/
#define TRIGGER_PORT        PORTB_ID
#define TRIGGER_PIN         PIN5_ID

#define ECHO_PORT           PORTD_ID
#define ECHO_PIN            PIN6_ID




/*******************************************************************************
 *                      Functions Prototypes                                   *
 *******************************************************************************/
/*  Description:
 *  ------------
➢ Initialize the ICU driver as required.
➢ Setup the ICU call back function.
➢ Setup the direction for the trigger pin as output pin through the GPIO driver.

• Inputs: None
• Return: None
 */
void Ultrasonic_init(void);

/*  Description:
 *  ------------
 *  ➢ Send the Trigger pulse to the ultrasonic.
• Inputs: None
• Return: None
 */
void Ultrasonic_Trigger(void);

/*  Description:
 *  ------------
 *   Send the trigger pulse by using Ultrasonic_Trigger function.
 *   ➢ Start the measurements by the ICU from this moment.
 *   • Inputs: None
 *   • Return: The measured distance in Centimeter.
*/
uint16 Ultrasonic_readDistance(void);

/*  Description:
 *  ------------
 *  ➢ This is the call back function called by the ICU driver.
 *  ➢ This is used to calculate the high time (pulse time) generated by the ultrasonic sensor.
 *
 *  • Inputs: None
 *  • Return: None
*/
void Ultrasonic_edgeProcessing(void);


#endif /* HC_SR04_H_ */
